# Numpy assignment

**Problem Statement-1**
**Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.**

**HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.**

### This problem statement is already given in assignment-3 
**so iam assuming here i should create vander matrix with numpy package**

## Without numpy package

In [1]:
def vander(x,*N_opt,increasing=False):
    if N_opt==():
        N=len(x)
    else:
        N=N_opt[0]
    l=[[j**(N-i-1) for i in range(N)] for j in x]
    for i in l:
        if increasing!=True:
            print(i)
        else:
            i.reverse()
            print(i)
vander([1,2,3,5])
vander([1,2,3,4],5)
vander([1,2,3,4,6],increasing=True)
vander([1,3,5,7],3,increasing=True)

[1, 1, 1, 1]
[8, 4, 2, 1]
[27, 9, 3, 1]
[125, 25, 5, 1]
[1, 1, 1, 1, 1]
[16, 8, 4, 2, 1]
[81, 27, 9, 3, 1]
[256, 64, 16, 4, 1]
[1, 1, 1, 1, 1]
[1, 2, 4, 8, 16]
[1, 3, 9, 27, 81]
[1, 4, 16, 64, 256]
[1, 6, 36, 216, 1296]
[1, 1, 1]
[1, 3, 9]
[1, 5, 25]
[1, 7, 49]


## With Numpy Package

In [2]:
import numpy as np
print(np.vander([1,2,3,5]))
print(np.vander([1,2,3,4],5))
print(np.vander([1,2,3,4,6],increasing=True))
print(np.vander([1,3,5,7],3,increasing=True))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    6   36  216 1296]]
[[ 1  1  1]
 [ 1  3  9]
 [ 1  5 25]
 [ 1  7 49]]


**Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below**

**i 1 2 3 4 5 6 7 8 9 10**

===== == == == == == == == == == ==

**Input 10 20 30 40 50 60 70 80 90 100**

**y1 25 = (10+20+30+40)/4**

**y2 35 = (20+30+40+50)/4**

**y3 45 = (30+40+50+60)/4**

**y4 55 = (40+50+60+70)/4**

**y5 65 = (50+60+70+80)/4**

**y6 75 = (60+70+80+90)/4**

**y7 85 = (70+80+90+100)/4**

**Thus, the moving average sequence has n-k+1=10-4+1=7 values.**

**Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.**

In [3]:
def moving_average(sequence,window):
    a=np.array(sequence)
    c=np.cumsum(a,dtype=float)
    c[window:]=c[window:]-c[:-window]
    return c[window-1:]/window
print(moving_average(np.arange(10,101,10),4))
print(moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3))

[25. 35. 45. 55. 65. 75. 85.]
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
